### ISSUE TITLE
Multiarch support

### ISSUE THREAD

**Issue by cdkrot** [cdkrot/ptrace-sandbox#1]
Add support for other architectures, at least x86_32, and x86_x32.

Todo: What happens if tracer compiled as one arch, and the tracee as other?

**Comment by vasalf** [comment]
Tracing 32-bit application under x86_64 architecture should work correctly, as strace can do it.

**Comment by cdkrot** [comment]
Yes.
... But user_regs_struct is defined differently on x86_64 and x86_32.

**Comment by cdkrot** [comment]
(Dropping old issues after revolution).
