### ISSUE TITLE
Brk(null)

### ISSUE THREAD

**Issue by cdkrot** [cdkrot/ptrace-sandbox#2]
> Program should call brk(NULL) before trying to change its break. Otherwise, it would be killed.

No other ways? We should create as little requirements to program, such that our presence is as invisible as possible.

**Comment by vasalf** [comment]
Hmm, I can't imagine a program doing correct memory management using brk without knowledge of its start break. Anyway, that looks suspicious. 

We really should know the program break position at start to monitor the memory usage. 

Anyway, we can try something else. There is a multiple choice of possible solutions:
1. We can try to call brk(NULL) while tracing. There must be such command in ptrace. 
2. Does execve(2) change the break position? If no, we can just get it from child.

**Comment by cdkrot** [comment]
2) Expectedly no, because execve replaces the current process code completely.
1) I believe we can (for example it is not problem for gdb), but the only known way to me is injecting  code into the process memory in runtime and setting the instruction pointer to this place.

Also, as you know, kernel supports multiple abis, you can get running the 32bit and 64bit programs on one machine in the same time. It's interesting what 64 bit tracer will see when it will try to trace 32bit program (multiarch problems to be discussed under #1)

**Comment by vasalf** [comment]
Isn't process code segment protected as read-only?

**Comment by cdkrot** [comment]
Should be.
But there other ways: allocating space via mmap, injecting to stack (it is executable, isn't it?)

There is some examples on code injection here http://www.opennet.ru/base/dev/ptrace_guide.txt.html (Use webarchive.org to access broken links).

**Comment by vasalf** [comment]
According to ptrace(2), we can use PTRACE_POKETEXT to modify process text segment, can't we?

**Comment by cdkrot** [comment]
Yes we can, but we don't know the text segments bounds, do we?

**Comment by vasalf** [comment]
We don't. But how are we supposed to jump from process to our code?

And is it possible to stop process at the very beginning of execution? Or we will just do it in the first call of brk?

**Comment by cdkrot** [comment]
Why we want to jump from process to our code? We want to issue brk(null) at the beginning of execution do we?
It is possible to do step-by-step tracing, where step is one asm instruction.

**Comment by vasalf** [comment]
513d295 now fixes this, the issue will be closed after pushing exp into master

**Comment by cdkrot** [comment]
(I believe it's done)
