### ISSUE TITLE
Check memory detection on speed and correctness

### ISSUE THREAD

**Issue by vasalf** [cdkrot/ptrace-sandbox#4]
I recently pushed some maximum memory detection into exp that seem to be quite working (commit 513d295). As it is mentioned in commit message, it has some stuff to be worked on.

Firstly, reading values from /proc can be not very fast, so we should test this code on speed.

Secondly, values that it shows are usually a hundred thousand bytes more than those shown by valgrind. Does it work correctly?

**Comment by vasalf** [comment]
Actually, values shown by max memory used are the same as ps aux shows, so we can accept that it works properly.

**Comment by cdkrot** [comment]
Okay, since it coincides with ps reported data we can believe it.
