### ISSUE TITLE
TL

### ISSUE THREAD

**Issue by cdkrot** [cdkrot/ptrace-sandbox#5]
Now it's time for implementing TL handling.

**Comment by cdkrot** [comment]
alarm(2) and /proc/<something>, I suppose.

**Comment by vasalf** [comment]
Maybe calculating time used by a program through time(0) inside the tracer would be better? Do values in /proc consider stops by ptrace?

**Comment by cdkrot** [comment]
time(0) and alarm(2) allow to measure "Wall time limit", which is not exactly connected with "time limit" (because it depends on scheduler and other things).

And, primarily, we want to measure "time limit", which is amount of clock(2)'s, or some field in /proc.

**Comment by cdkrot** [comment]
(Dropping old issues after revolution).
