### ISSUE TITLE
Multi threads/process support

### ISSUE THREAD

**Issue by cdkrot** [cdkrot/ptrace-sandbox#6]
Unfortunately, we need multithread / process support because java <s>sucks</s> creates many threads even for "hello world".

What exactly has to be done: multithread requires some modifcations to tracing_utils.c, because we need to store not boolean flag "are we inside syscall", but Set of pids in syscall.

So we need Set (some code allready done, but looks pretty poor - templates via defines...).

So, finish templated Set implementation, or drop templates for simplicity?

**Comment by vasalf** [comment]
Implementation of complex structures using defines to template parameters looks quite ugly. Do we have another ideas?

**Comment by vasalf** [comment]
By the way, how many threads do we allow at maximum? I mean, do we really need a binary tree or something like that?

**Comment by cdkrot** [comment]
Implement it without templates? We need only set < pid >.

Since the restricting code is not implemented, the policy is not set.

Measurements show, that java wants about 7 thread, something about 10 is enough, I suppose.

**Comment by cdkrot** [comment]
Yes, that means, that we can use array implementation of set.

**Comment by vasalf** [comment]
Than that would be not very ugly; for example, we don't need a comparator. 

Templates are useful when we need the same structure in many situations. The problem is, that we don't know it before we write it. 

I suggest to write it without templates now and re-write it when we will need the same structure somewhere else.

**Comment by vasalf** [comment]
Of course, we _allow_ to use an arbitrary amount of threads. But that is not a problem that the tracer will slow down if he see thousands and thousands of threads.

**Comment by vasalf** [comment]
As long as most of code is already written in exp, there is no reason to re-write it now and than re-write it again. I think, we can just leave it as it is.

So now we have to add tests to set (maybe, written in C++ and just stressed with what we have) and than we can push set into master (#7).

**Comment by cdkrot** [comment]
Okay, but it is incomplete a bit.

And even it's compilability is not verified.

Yes, we probably need to write tests to it.

**Comment by cdkrot** [comment]
(Dropping pre-revolution issues)
