### ISSUE TITLE
Too long processing for syscalls

### ISSUE THREAD

**Issue by vasalf** [cdkrot/ptrace-sandbox#8]
New demo in b0b4e8d (million-of-mmaps) works for 0.2 seconds on my machine but it works about a hundred(!) times longer under newdetect. Need to be fixed.

**UPD**: Solution with kprobes get x2 slowdown, which is much better and seems to be unfixable.

**Comment by cdkrot** [comment]
It is understandable, because newdetect makes a lot of terminal IO, which is slow.

**Comment by cdkrot** [comment]
Suggestion: separate "newdetect", which should be just detector and "sandbox", which for restricting stuff.

**Comment by vasalf** [comment]
No! It works for 20 seconds even with all printfs commented out!

**Comment by vasalf** [comment]
How would it help us?

**Comment by cdkrot** [comment]
Okay, i thought this overhead is because of logs.

Maybe we want to try -O2 conpilation on detector.

And if it wouldn't help, that we will go for kernel module.

**Comment by vasalf** [comment]
It actually didn't help a lot. Still about **20** seconds **without memory limit detection and fprintfs**. And I can't imagine a solution through kernel modules.

**Comment by cdkrot** [comment]
Without memory detection? Without reading /proc at all?

**Comment by vasalf** [comment]
Yep

**Comment by vasalf** [comment]
```
$ time ./bin/main/newdetect ./bin/demos/million-of-mmaps &> /dev/null

real    0m20.332s
user    0m1.285s
sys 0m21.189s
```

According to time output, most of the time is spent in system. I suppose that we have nothing to do with it.

**Comment by cdkrot** [comment]
That means that only possible way of boosting without altering with kernel is to re-read ptrace(2) and think what can be done in tracing_utils.c

**Comment by vasalf** [comment]
I bet thais is a general ptrace issue. I think, wontfix label would be reasonable there. strace works as much as 2.5 times longer than our program with printfs and memory detection enabled:

```
$ time strace bin/demos/million-of-mmaps &> /dev/null

real    1m17.063s
user    0m16.472s
sys 1m11.064s
```

The solution would be too hard. But I believe it exists! Look at valgrind time:

```
$ time valgrind bin/demos/million-of-mmaps &> /dev/null

real    0m8.950s
user    0m7.504s
sys 0m1.447s
```

So theoretically that can be done. According to [that paper](https://www.usenix.org/legacy/events/usenix05/tech/general/full_papers/seward/seward_html/index.html), valgrind _recompiles the client's code, ..., in a just-in-time, execution-driven fashion_.

But according to project name, still wontfix :)

**Comment by cdkrot** [comment]
To sum up we have following ways of resolution:
- Ignore, at least for now =(. Let's say, that machine time is cheap.
- Go to seccomp. It was written exactly for sandboxing, but it will require root.
- Go kernel. Write some kernel module to boost execution (but it is not obvious what it should be doing).
- Go valgrind? The boost it shows is great, though runtime code recompilation doesn't sound pretty attractive.
- Go virtualization? Maybe virtualization tools have found some good way of sanboxing?

**Comment by cdkrot** [comment]
Found pretty interesting documentation for valgrind-based development over there, we may want to consider it.

(For example smallest possible slowdown under valgrind is 5, which is much better than ptrace's 75).

http://www.valgrind.org/docs/manual/valgrind_manual.pdf

**Comment by vasalf** [comment]
According to our personal conversation, we both agree that variant with writing a kernel module is preferable. But how could we control ML through modules? And even catch forbidden syscalls?

**Comment by vasalf** [comment]
There are many solutions over here: http://stackoverflow.com/questions/13876369/system-call-interception-in-linux-kernel-module-kernel-3-5

I think, some of them do work in 4.4. 

And - in the best answer on StackOverflow - there replacing of system calls is described. So cher patch can actually be put into the kernel in runtime. But that's not what we actually want, is it?

**Comment by vasalf** [comment]
This is fixed in 79472fe. Memory detection through kprobes is working about 1.13 seconds, which is much better. Merge to master and close the bug?

**Comment by cdkrot** [comment]
While x5 speed downgrade is better x100 speed downgrade, i am still thinking if we can make it better.

**Comment by cdkrot** [comment]
After fixing mmap demo in (6eb03301a3) the working time is as in following:

> (Without module):
> real    0m0.533s
> user    0m0.034s
> sys     0m0.499s
> 
> (With module)
> real    0m1.172s
> user    0m0.035s
> sys     0m1.138s

**Comment by vasalf** [comment]
I'm not sure if we are able to make it better. Now we catch mmap in the **kernel space**...
Even 2x latency is much better than 60x and 100x that we had with ptrace. I remind, we are talking about code that does **only** mmaps. Usually, code on C does it very few times, you know.
And, as you see there, a single mmap works pretty long (0.5 s for a million of them), so no **good** code would call mmap so many times.
Wontfix?

**Comment by cdkrot** [comment]
(We have done everything we can for now)
