### ISSUE TITLE
Write a kernel module to read values that are now located in /proc

### ISSUE THREAD

**Issue by vasalf** [cdkrot/ptrace-sandbox#9]
New demo in  b0b4e8d works for 22 seconds under old version of newdetect (not detecting memory) and for 30 seconds under latest version in exp. So reading values from /proc really **is too slow**. Besides, that realisation adds a restriction on enabling procfs in kernel, which is useful but not mandatory.

cdkrot suggested to write a kernel module to read that values faster (as long as they are in proc, they are also located in kernel).

It's a long-time issue, I don't say that we should write it right now. But time we need to process syscall sucks.

**Comment by cdkrot** [comment]
Inactual, we are writing module now, but not for that reason.
